import numpy as np
# ^^^ pyforest auto-imports - don't write above this line
![](images/la.jpg)

### Load in NumPy (remember to pip install numpy first)

In [14]:
import numpy as np

### The Basics

In [20]:
arr = np.array([[1,4,7],[2,3,5],[2,3,5],[2,3,5]])
print(arr)

[[1 4 7]
 [2 3 5]
 [2 3 5]
 [2 3 5]]


In [35]:
# create an integer array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [28]:
# create a float array
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]
 [6. 5. 4.]]


In [26]:
# Get Dimension
arr.ndim

2

In [29]:
# Get Shape
b.shape

(3, 3)

In [30]:
# Get Type
a.dtype

dtype('int32')

In [31]:
# Get total size
a.nbytes

12

In [36]:
# Get number of elements
a.size

5

### Accessing/Changing specific elements, rows, columns, etc

In [38]:
arr = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [42]:
# Get a specific element [row, column]
arr[1,6]

14

In [46]:
# Get a specific row 
arr[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [50]:
# Get a specific column
arr[:, 4]

array([ 5, 12])

In [56]:
arr[0,1:-1:3]

array([2, 5])

In [58]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:1]

array([2, 3, 4, 5, 6])

In [24]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

### Initializing Different Types of Arrays

In [10]:
# All 0s matrix
np.zeros((2,3))

<IPython.core.display.Javascript object>

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2,3))

<IPython.core.display.Javascript object>

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
# All 1s matrix
np.ones((4,2,2))

<IPython.core.display.Javascript object>

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [13]:
# Any other number
np.full((3,3), 11)

<IPython.core.display.Javascript object>

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

In [14]:
# Any other number (full_like)
np.full_like(a, 4)

<IPython.core.display.Javascript object>

array([[4, 4],
       [4, 4]])

In [18]:
np.random.rand(5,2) #uniform distribution

<IPython.core.display.Javascript object>

array([[0.7100726 , 0.47091384],
       [0.09040786, 0.66280162],
       [0.28226997, 0.5646576 ],
       [0.95539005, 0.3306128 ],
       [0.98475146, 0.63561102]])

In [16]:
np.random.randn(5,2) #normal distribution

<IPython.core.display.Javascript object>

array([[ 1.70893126,  0.08443298],
       [ 0.35428382,  0.29373366],
       [ 1.42804862, -1.04431742],
       [-0.35621961, -0.13975293],
       [ 0.07224299,  1.04202362]])

In [56]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.07805642, 0.53385716],
       [0.02494273, 0.99955252],
       [0.48588042, 0.91247437],
       [0.27779213, 0.16597751]])

In [21]:
# Random Integer values
np.random.randint(1,8, size=(3,3))

<IPython.core.display.Javascript object>

array([[4, 4, 6],
       [3, 2, 6],
       [2, 5, 3]])

In [24]:
# The identity matrix
np.identity(3)

<IPython.core.display.Javascript object>

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [12]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [ ]:
# (rowxcol)
#(3x3) (3x2)

![](images/matrixTimes.gif)

![](images/matrices-demo.gif)

In [40]:
# Dot product
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]])
np.dot(a,b)
# Most important concept of deep learning

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([[37, 40],
       [85, 92]])

### arange

Return evenly spaced values within a given interval.

In [42]:
np.arange(0,10)

<IPython.core.display.Javascript object>

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(0,10,2)

<IPython.core.display.Javascript object>

array([0, 2, 4, 6, 8])

### linspace
Return evenly spaced numbers over a specified interval.

In [47]:
np.linspace(0,10,3)

<IPython.core.display.Javascript object>

array([ 0.,  5., 10.])

In [35]:
np.linspace(0,10,100)

<IPython.core.display.Javascript object>

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [48]:
np.eye(4)

<IPython.core.display.Javascript object>

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [49]:
arr = np.array([10, 12, 41, 17, 49,  2, 46,  3, 19, 39])

<IPython.core.display.Javascript object>

In [50]:
arr.max()

49

In [52]:
arr.argmax()

4

In [53]:
arr.argmin()

5

## Shape

Shape is an attribute that arrays have (not a method):

In [54]:
# Vector
arr.shape

(10,)

In [59]:
# Notice the two sets of brackets
arr.reshape((1,10))

array([[10, 12, 41, 17, 49,  2, 46,  3, 19, 39]])

##### Be careful when copying arrays!!!

In [62]:
# Copy an Array
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(b)

[100   2   3]


### Mathematics

In [63]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
# array to array addition

In [64]:
a + 2

array([3, 4, 5, 6])

In [65]:
a - 2

array([-1,  0,  1,  2])

In [66]:
a * 2

array([2, 4, 6, 8])

In [67]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [68]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [69]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [70]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [71]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [72]:
np.tanh(a)

array([0.76159416, 0.96402758, 0.99505475, 0.9993293 ])

In [73]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [74]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

### Lists 

In [81]:
# create a list
lst = [1,2,3,4,5,6]
print(type(lst))

<class 'list'>


In [84]:
# contact a list
newlst = [7,8,9]
lst+newlst

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# adding lists
lst + lst

In [ ]:
# Scalar Multiplication
lst * 4

##### Linear Algebra

In [62]:
c = np.eye(4)
c

<IPython.core.display.Javascript object>

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [63]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

1.0

In [133]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [64]:
stats = np.array([[1,2,3],[4,5,6]])
stats

<IPython.core.display.Javascript object>

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
np.min(stats)

<IPython.core.display.Javascript object>

1

In [66]:
np.max(stats, axis=1)

<IPython.core.display.Javascript object>

array([3, 6])

In [67]:
np.sum(stats, axis=0)

<IPython.core.display.Javascript object>

array([5, 7, 9])

In [68]:
# standard diviation
np.std(stats)

<IPython.core.display.Javascript object>

1.707825127659933

In [69]:
# variance
np.var(stats)

<IPython.core.display.Javascript object>

2.9166666666666665

### Miscellaneous
##### Load Data from File

In [70]:
file = np.genfromtxt('data.txt',delimiter=',')

<IPython.core.display.Javascript object>

In [78]:
file = file.astype('int16')

In [79]:
print(file)

[[  1  13  21  11 -60  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33  -2  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 -25  11   2   1  78   0   1   2   9   8   7   1  76  88]]
